### ISSUE TITLE
retry only on specific exception?

### ISSUE THREAD

**Issue by petrsigut** [y-yagi/minitest-retry#11]
We are trying to solve our integration tests sometimes failing on Net::ReadTimeout: Net::ReadTimeout exception.

Do you think it would be good idea to list exceptions on which minitest-retry would try again? 

In similar way :exceptions_to_retry in https://github.com/NoRedInk/rspec-retry

**Comment by y-yagi** [comment]
Thanks for your report. 
`:exceptions_to_retry` looks good. I will add.

**Comment by y-yagi** [comment]
Fixed by #13
