### ISSUE TITLE
Minitest::Retry.on_failure is not triggered when exceptions_to_retry option is given.

### ISSUE THREAD

**Issue by devvpm** [y-yagi/minitest-retry#22]
I have this code to take a screenshot on failure.

```
Minitest::Retry.on_failure do |klass, test_name|
    puts "Theres an error"
    if $browser
        $browser.screenshot.save("test/screenshots/#{host_name}_#{klass}_#{test_name}.png")
        logout()
    end
end
```

and I initialized retry like this, 

```
Minitest::Retry.use!(
    retry_count:  1,
    verbose: false,
    io: $stdout,
    exceptions_to_retry: [Watir::Wait::TimeoutError]
  )
```
Expectation is to take a screenshot every time a test fails. But that does not happen now, It used to work when there was no `exceptions_to_retry` option give.

**Comment by y-yagi** [comment]
`on_failure` callback executes only when retrying. 
In the above setting, `on_failure` is executed only when `Watir::Wait::TimeoutError` occurs. Will not be executed even if `Watir::Wait::TimeoutError` occurs?

**Comment by devvpm** [comment]
It is triggered when `Watir::Wait::TimeoutError` occurs. Is there a workaround where test should be re-run only on that exception but `on_failure `should be called on all the failures?

**Comment by devvpm** [comment]
I think `on_failure `should be triggered on all the failures, irrespective of `exceptions_to_retry` option.

**Comment by y-yagi** [comment]
No there is not.  The callback provided by `minitest-retry` is only for retrying the test.

**Comment by y-yagi** [comment]
This is intentional behavior(at least in currently). So I close. Thanks!
