### ISSUE TITLE
Is there a way to suppress error screenshots until the last failure?

### ISSUE THREAD

**Issue by brandoncordell** [y-yagi/minitest-retry#37]
We use minitest-retry to get through some flaky system tests which all end up passing by the time they're retried but there's still a lot of output on the screen for screenshots of the initial failures. I would love a way to hide those until the last failure if possible.

**Comment by y-yagi** [comment]
We don't have the features so far because screenshots are taken by gems(not minitest's feature) and `minitest-retry` doesn't know other gems behavior.

This is just curious, but how do you take screenshots? Do you use features that is provided by Rails?

**Comment by brandoncordell** [comment]
@y-yagi We're just using a basic Rails setup. Failures get a screenshot added to tmp/screenshots. I don't think we have anything specifically configured for it.

**Comment by y-yagi** [comment]
Thanks. That means you use Rails's screenshot feature. I would say again, that's not minitest's feature. That's provided by Rails.
