### ISSUE TITLE
Is there a way to also get setup to run for each retry?

### ISSUE THREAD

**Issue by sipani909** [y-yagi/minitest-retry#39]
Currently this gem retries from the test method if a test fails. Is there or can there be an optional arg added to make it run from setup if a test fails?

**Comment by y-yagi** [comment]
We don't have the feature it for so far. The current implementation assumes re-run only tests. So it might need some refactoring to support it.
We can set callback that will call a test is retried. Isn't that enough?
https://github.com/y-yagi/minitest-retry?tab=readme-ov-file#callbacks
